### ISSUE TITLE
Vagrant Provision Issue (Invalid User: 502)

### ISSUE THREAD

**Issue by sshami** [forumone/web-starter#201] opened 2016-05-31 22:37 UTC
![screen shot 2016-05-31 at 6 25 48 pm](https://cloud.githubusercontent.com/assets/2728077/15692737/31269a82-275e-11e6-884f-a8df187f4d0b.png)

![screen shot 2016-05-31 at 6 26 10 pm](https://cloud.githubusercontent.com/assets/2728077/15692741/38be841c-275e-11e6-8434-8f6d9d4f71d7.png)

I was able to provision successfully on my personal laptop (Macbook), however, I'm getting the above errors trying to provision on my Mac desktop.

**Comment by arh1** [comment] 2016-05-31 23:25
Definitely seems related to #202 in that 502 looks like a bogus uid (the uid on the host, that's incorrectly passed through to the VM, but meaningless there).

**Comment by boy412** [comment] 2016-08-09 12:27
I am attempting to help @sshami with this issue. It is reproducible on two different systems, both of which are multi-user setups (Mac OS 10.x). I agree this seems related to #202. Was there a fix for this? I am at the limits of my troubleshooting skills for this issue.

**Closed as completed** 2019-05-21 18:55 UTC
