### ISSUE TITLE
Unable to connect to MySQL using web/web

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#244] opened 2016-08-04 13:49 UTC
```
[vagrant@localhost ~]$ mysql -u web --password=web
Warning: Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'web'@'localhost' (using password: YES)
```

`generated.sls` looks like:

```
mysql:
  mysql_version: mysql56u
  database:
    - web
  user:
    web:
      password: 'web'
      host: '%'
      databases:
        - database: web
          grants: ['all privileges']
```

**Comment by mshade** [comment] 2016-08-04 14:52
So, we are granting on '%' to try to allow connecting from the host through the vagrant forwarded port. That works! Except, it doesn't work when connecting through socket, which is default when you specify -h localhost or no -h option at all.

This works, while -h localhost doesn't:

```
mysql -u web -h 127.0.0.1 -pweb
```

**Comment by mshade** [comment] 2016-08-04 15:08
This is a result of https://bugs.mysql.com/bug.php?id=31061 - "not a bug" that I think totally is. Very fun. I will see about removing the anonymous accounts that cause this issue.

**Comment by mshade** [comment] 2016-08-04 15:11
Ok, this should be fixed in 02dfef0

**Comment by wwhurley** [comment] 2016-08-04 17:26
So should sites connect using 127.0.0.1 instead of sockets in the future?

**Comment by mshade** [comment] 2016-08-04 17:27
It doesn't matter - sites can use either socket or tcp. The formula will now remove the '' anonymous users which means the connection string should work the same, regardless of socket or tcp.

**Closed as completed** 2016-08-04 17:26 UTC
